language: python
python:
- 3.6.8
stages:
- Quality
- Publish
install:
- make install-dev
jobs:
  include:
  - stage: Quality
    name: lint
    script: make lint
  - name: tests
    script: make test
  - stage: Publish
    script: skip
    deploy:
      provider: pypi
      user: "__token__"
      distributions: sdist bdist_wheel
      password:
        secure: kWew3Qb3pqAHiU/MWd3dPDT3+MDt6oNwgsymnwMlGeYFvD3cpjdwxLBkcKpKvD8GeFh8Divub1Qoq/CI7cJrBKVHTVLyC7ggTQXUZrvaG2ZdJws63zWUrg32Dj1+tENO2Sl3XEht0u+k1M5dlHOaTmHjDXaD+L9mK7NfRQYHvTRB2xuce7Db8WgktNYrCXc7wvhYXCicFihBBCVvFT3WvptUUy1aqD6gsVyAWqb8xTzMS10QWCgVBQd/sHhYLsAuOGEQGf2Y46B79soAmOmYEn4k/76hH9oZ4JtU1n8AClSxFAXVnMbHeuaC7pkmwsZ8KiF90Odv+O3zunMJgOuzXPoh7oWKDEOcb5vOxqGDfjlYyR63ocHULtpZ5eIRtKN6ECX23D0tqun9AVZfyn8QX3jkrMsO2mvVe3l5HAkHsBv5EDWeyLhxgl/60XpxcNFtL49LNm4QIjhYkxohnuvbhpBqiMptTJHI0UAR/z41P0UZg/qR6AdYLjurioD50NLDnXQ0NUVe5kOZq1gDGL4HRwGW55M+q5KgVAo65FPWw5chRlfrIUSv/dyTIHBYD4zjR8uht9yD8KsvBVW0mi30QGXCGG+mch5IUnoYVyUkIafsa2iniphoLAbN6OU75c6tN0SYLjEJv6Tej0cktqpANhfp3VJCjUcSSZGPo/mtVR8=
      on:
        tags: true
    if: tag IS present
after_success: coveralls
